### ISSUE TITLE
Failure to process some tracks in bulk

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [jarredou/MVSEP-MDX23-Colab_v2#12]
I am using vr2.3 and it is fine until It falls to process some particular file:

/content/MVSEP-MDX23-Colab_v2
GPU use: 0
started!

Options: 
BigShifts: 11

weight_InstVoc: 10.0
weight_VitLarge: 7.0

overlap_InstVoc: 1
overlap_VitLarge: 1

use_VOCFT: False
vocals_only: True
output_format: FLOAT

Loading InstVoc into memory
Loading VitLarge into memory
Go for: /content/drive/MyDrive/Music/Bullet For My Valentine/2010 - Fever/01. Your Betrayal.flac
Input audio: (2, 12848976) Sample rate: 44100
Processing vocals with VitLarge model...
100% 11/11 [01:02<00:00,  5.64s/it]
Processing vocals with MDXv3 InstVocHQ model...
100% 11/11 [02:00<00:00, 10.92s/it]
Processing vocals: DONE!
File created: /content/drive/MyDrive/Results/01. Your Betrayal_vocals.wav
File created: /content/drive/MyDrive/Results/01. Your Betrayal_instrum.wav
Go for: /content/drive/MyDrive/Music/Bullet For My Valentine/2010 - Fever/02. Fever.flac
Traceback (most recent call last):
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 816, in <module>
    predict_with_model(options)
  File "/content/MVSEP-MDX23-Colab_v2/inference.py", line 711, in predict_with_model
    audio, sr = librosa.load(input_audio, mono=False, sr=44100)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 192, in load
    y = resample(y, orig_sr=sr_native, target_sr=sr, res_type=res_type)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 632, in resample
    ratio = float(target_sr) / orig_sr
ZeroDivisionError: float division by zero

**Comment by deton24** [comment]
It's 4:53/5:01 audio. Maybe a bit longer than most files, so maybe changing
some parameters might do the trick, but have you checked whether that file
is correctly separated when not in bulk?

czw., 8 lut 2024 o 01:16 Mohammed Mehdi TBER ***@***.***>
napisał(a):

**Comment by MohammedMehdiTBER** [comment]
Even with selecting the conflicting track alone, the same error happens:
[image: image.png]


*A technical, translator, and moderate Sunni Muslim. The antidote of
hypocrites, disbelievers and grooming perisher.*

**Comment by deton24** [comment]
Just to be completely sure, use the song from other source to ensure that
your input file is 100% fine.
It stopped pretty soon for this file, and before any separation process, so
probably setting e.g. BigShifts to 1 or decreasing overlap won't help.

You can also paste log of your file from MediaInfo.

czw., 8 lut 2024 o 19:04 Mohammed Mehdi TBER ***@***.***>
napisał(a):

> Even with selecting the conflicting track alone, the same error happens:
> [image: image.png]
>
>
> *A technical, translator, and moderate Sunni Muslim. The antidote of
> hypocrites, disbelievers and grooming perisher.*
>
>

**Comment by MohammedMehdiTBER** [comment]
I think those files are processed the same way by the uploader, knowing
this is a declipped version of the album, and It does not happen with all
the files.
well, I have just checked the conflicted file  with mediainfoand It seems
to be a broken file  that did not get downloaded correctly and I cannot
listen to it even.
seems an issue with torrent. sorry for interruption




*A technical, translator, and moderate Sunni Muslim. The antidote of
hypocrites, disbelievers and grooming perisher.*
