### ISSUE TITLE
Question about future development of the model

### ISSUE THREAD

**Issue by Bebra777228** [jarredou/MVSEP-MDX23-Colab_v2#17]
Hi! I really enjoyed your Colab Notebook and I have a couple of questions:

1. **Is there a plan to implement a feature for adding custom separation models?**
2. **Will DeEcho-DeReverb and DeNoise models be added for more efficient separation?**

Thank you in advance for your answer!

**Comment by deton24** [comment]
You can use these VR models here
https://huggingface.co/spaces/r3gm/Ultimate-Vocal-Remover-WebUI

sob., 13 kwi 2024, 20:12 użytkownik Jarredou ***@***.***>
napisał:

**Comment by Bebra777228** [comment]
With each new model, the load on the GPU increases and can reach 13-14 GB. This leads to a slowdown in the processing process. I would like to know if optimization will be implemented to reduce the load on the GPU?
